v0.0.2: new build script; sem vers; etc

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,28 +1,29 @@
 #!/bin/bash
-# Make
-set -euo pipefail  # Deliberately fail if any errors, as with other languages
-PRG=days
+# build
+# Make the binary and place in the PATH
+set -euo pipefail  # Fail on any error
+Prg=`head -1 go.mod | awk -F'/' '{print $NF}' | awk '{print $NF}'`
 case "$OSTYPE" in
-    "linux-gnu"* )
-        echo "Linux build ..."
-        go build -ldflags "-s -w" -o $GOPATH/bin/$PRG
-        ls -l $GOPATH/bin/$PRG
-        ;;
-    "darwin"* )
-        echo "macOS build ..."
-        go build -ldflags "-s -w" -o $GOPATH/bin/$PRG
-        ls -l $GOPATH/bin/$PRG
-        ;;
-    "msys"* )
-        echo "Windows build ..."
-        go build -ldflags "-s -w" -o $GOPATH/bin/${PRG}.exe
-        ls -l $GOPATH/bin/$PRG
-        ;;
-    * )
-        echo "OSTYPE=$OSTYPE is unknown!"
-        echo ""
-        echo "Options are: darwin*, linux-gnu*, and msys* (GitBash on Windows)" 
-        echo ""
-        exit 1 ;;
+    "linux-gnu"* ) printf "==> OS = Linux\n" && BIN=$GOPATH/bin/${Prg} ;;
+    "darwin"* )    printf "==> OS = macOS\n" && BIN=$GOPATH/bin/${Prg} ;;
+    "msys"* )      printf "==> OS = Windows with GitBASH\n" && BIN=$GOPATH/bin/${Prg}.exe ;;
+    * )            printf "==> OS = \"$OSTYPE\", unknown! (Options are Linux, macOS, or Windows with GitBASH)\n" && exit 1 ;;
 esac
+go fmt
+go mod tidy
+go test ./...
+go build -ldflags "-s -w" -o $BIN
+ls -l $GOPATH/bin/$Prg
+
+printf "\n==> Version in main.go:\n"
+grep "prgver.*=" main.go
+printf "\n==> HEAD of go.mod:\n"
+head go.mod
+
+printf "\n==> Last 3 tag versions, sorted semantically:\n"
+git tag | sort -t "." -k1,1n -k2,2n -k3,3n | tail -3
+CurrentTag=`git tag | sort -t "." -k1,1n -k2,2n -k3,3n | tail -1`
+printf "\n==> To publish, do below one-liner, advancing tag version and updating comments accordingly:\n\n"
+printf "Tag=$CurrentTag && Prg=$Prg && git add . && git commit -m \"\$Tag: updates\" && git tag \$Tag && git push origin \$Tag && git push\n\n"
+
 exit 0
